import type { NextPage } from 'next';
import { PropsWithChildren } from 'react';
import Image from 'next/image';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { IInitData } from '../types/Types';

type PageProps = PropsWithChildren<{ data: IInitData }>

const Home : NextPage<PageProps> = ({ data }) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {console.log(data)}
    <div className={styles.bg}>
      <p>test</p>
      <Image
        src='https://images.unsplash.com/photo-1524961336682-be0a68445b3c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3732&q=80'
        layout='fill'
        />
      {data.images.map((p: string) => <Image
        src={p}
        layout='fill'
        />)}
    </div>
  </div>
);

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('http://localhost:3000/api/')
  const data : IInitData = await res.json()
  console.log(data);
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      data,
    },
  }
}

export default Home;
